version: "3"

services:
  scraper:
    container_name: scraper_app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
      - ../reflex.conf:/reflex.conf
      - ../scripts/dev.sh:/dev.sh
    ports:
      - "5000:5000"
    entrypoint: /dev.sh
    environment:
      - SCRAPER_DATABASE_URL=mongodb://scraper_db:27017/news_scraper
      - SCRAPER_DATABASE_NAME=news_scraper
      - PYTHONPATH=/usr/local/lib/python3.6:/app/dependencies
      - ENVIRONMENT=dev
    working_dir: /app
    depends_on:
      - scraper_db
    links:
      - scraper_db
  scraper_db:
    container_name: scraper_db
    image: mongo
    volumes:
      - ./db_data:/data/db
    ports:
      - "27018:27017"
    logging:
      driver: none
